dist: trusty
sudo: 'false'
language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
  email:
    secure: VOBPzO3Wo4dZaT6u+VMzZFvt23fJdp+UlkGqb1sX+rjk9PYQmPADELpeHklB2XC9CAmDn8PG8CSzs0RJJbZqG9Uhr2OddsonCRbdQtBp4kX+tIFl6M+ZKnSYAscWf4iQp2aiTSBGfWgLoDzi9/Aw9tS63pzTZzaGifWTjQnL6fGnH423gSyibqubIaANZSSjwZWptNAluLcS5biccx120JWj6/wWfqRIsCo+nciTt4lYBw9gGzf+5AfFGP8sYZmsh4sI3Zmae/Ju6v8jHILeQSLdj+WFibyM3XFn1qvpXkHRn8HUQHhpos1sUTqPXQ+HrlEuMdJ87/VMfwO3Ea6lGOqh9T1IwMzjss/cx+N+m0gc6lhFEYsi+4WLt7isOU6R9Mo82x7KhHeub6KhJl62hlMykFsHUDYtP4nZAe7uKnDxw61ADNS32nEAjKtlAJGD1szOSrHWQL5QMpzc8lBGwLQu51aLU+rRpyuoHN6LZLLx1M3f4WOFQgDq1R5PT6Qw6XrqKtfbStGB6dMFHC09+9oXwuxI/eqNbQsbDu6r+ZdRE6TP3/lTf0AB4DaZdN3CaBcAk4q3Q+Mfaj4uihuVNnoHJ29RzNFjWUxbm/+42Jg/gbWjP/7XwkTYbgq7d4NFu+JOLyIQwFwQmxbbv0rLNoKYNv4qDF+8l8n50wb8L5Y=
  api_key:
    secure: 3Qqu1k++i9Djmc5I2z7msJqKIpnZel4oO2b2PAtI1wRdPnMP9yYaR4ecNQb1y6Dydj44bDtVE6SpmlMYxUgHgZrDymJRTRJffujHx57mSvROlCNWJZigrq3Cvn9HnWscUm9DH1AprurU9o/GW4F+U2ozvesKOg0O0DEsEIQRMZld54rfjj2r0icQewcP3+GjBT7KRBLILj6UVMxVm7MKveWi3Ja/9IDCZx4FUkzcZ/WPpOQl462B8h4uNT/T9+t/LNApghWQ77ibCTy/iundAMrtU+qAw4J3exVA3+FGePsbSrI4mSMCsPwu8WHy8Akg8Hesx0AtQh2IRloxywhlDfir2WbnNpldJuFM8UCqbtvs7kIfWTGpanW6dTqiB82OsB+xw/2KnktqAHn06j/+6K3mG86Tj4DdR11oKu3MebXWV8fELd0twCso3PgC5Vk6L0r9O+vVA5bZAdpy860xAdG1gturCZpjycZopB86E1CWls+nPqzmh2cLhqVLvYdAA84yRFEWLjRNBvFhdP2k7sCpoyPQuURI1Wkh9GBjSE1PxkwHa14zmIgmBV3HAdSXr2ASpbbzqV8FjlUFa5mnCMb5fYYToSDoy7vrgyRbLzKaHaXe5U7IaJmjtfbsMXe17qo7niXBqMD/t1D/NxQ8Ofwn6ZV8TKwDCQjMPY6+pRw=
